### ISSUE TITLE
Please enable support for Android Studio 3.0 gradle plugin

### ISSUE THREAD

**Issue by lsuhov** [Vigi0303/fat-aar-plugin#14]
Hi,

Currently the highest version of gradle plugin that works for our project is com.android.tools.build:gradle:2.3.3.

Can you take a look at the latest gradle plugin from Android Studio 3?
It throws the following exception:
Caused by: java.lang.RuntimeException: Can not find task prepareDebugDependencies!
	at me.vigi.fataar.VariantProcessor.processVariant(VariantProcessor.groovy:36)
	at me.vigi.fataar.VariantProcessor$processVariant$0.call(Unknown Source)
	at me.vigi.fataar.FatLibraryPlugin.processVariant(FatLibraryPlugin.groovy:95)
	at me.vigi.fataar.FatLibraryPlugin.this$2$processVariant(FatLibraryPlugin.groovy)
	at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:579)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:506)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
	at me.vigi.fataar.FatLibraryPlugin$_apply_closure1_closure3.doCall(FatLibraryPlugin.groovy:30)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:154)
	at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
	at me.vigi.fataar.FatLibraryPlugin$_apply_closure1.doCall(FatLibraryPlugin.groovy:29)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy32.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:75)

Thank you

**Comment by vigidroid** [comment]
Hi lsuhov,
android gradle plugin version 2.2.3 and later is not supported by fat aar plugin. Please check your configuration file.

the plugin version used with android studio 3.0 may be higher than 2.2.3 by default, that I did't install it and don't know it. If thus, you can manually change it.
